#!/usr/bin/env ruby
require 'uri'
require 'nokogiri'
require 'open-uri'
require_relative 'lib/daumdic'

# Handle ^C gracefully
trap('SIGINT') { puts; exit 1 }

# REPL
puts 'Daum 사전'
puts ''
loop do
  print '> '
  input = gets

  # Handle ^D gracefully
  if input.nil? then puts; exit end

  result = search(input)
  puts result unless result.nil?
end
